use anchor_lang::prelude::*;
use anchor_spl::{
    associated_token::AssociatedToken,
    token::{self, Mint, Token, TokenAccount, Transfer},
};

use crate::{
    constants::{CONFIG_SEED, MIN_CLIFF_SECONDS, VAULT_SEED, VAULT_TOKEN_SEED},
    errors::GeckoError,
    state::{GeckoConfig, SponsorVault, VaultStatus},
};

/// Initialize a campaign vault and deposit funds atomically.
///
/// Combines `init_vault` + `deposit` into a single transaction.
/// The sponsor signs once and the vault is immediately funded — no
/// second transaction required to move from init to active+funded.
///
/// Parameters:
/// - `campaign_id`: unique u64 per sponsor (generated by API timestamp)
/// - `cliff_seconds`: lock duration in seconds from now (min MIN_CLIFF_SECONDS)
/// - `end_seconds`: campaign end in seconds from now (must be >= cliff_seconds)
/// - `amount`: token amount to deposit (6 decimals for USDC)
pub(crate) fn process(
    ctx: Context<InitAndDeposit>,
    campaign_id: u64,
    cliff_seconds: i64,
    end_seconds: i64,
    amount: u64,
) -> Result<()> {
    require!(cliff_seconds >= MIN_CLIFF_SECONDS, GeckoError::DurationTooShort);
    require!(end_seconds >= cliff_seconds, GeckoError::InvalidTimestamps);
    require!(amount > 0, GeckoError::ZeroAmount);
    require!(
        ctx.accounts.config.allowed_mints.contains(&ctx.accounts.mint.key()),
        GeckoError::UnsupportedMint
    );

    let now = Clock::get()?.unix_timestamp;

    // Init vault
    let vault = &mut ctx.accounts.vault;
    vault.sponsor = ctx.accounts.sponsor.key();
    vault.mint = ctx.accounts.mint.key();
    vault.vault_token_account = ctx.accounts.vault_token_account.key();
    vault.principal = 0;
    vault.total_yield_routed = 0;
    vault.gecko_fee_bps = ctx.accounts.config.fee_bps;
    vault.cliff_ts = now.checked_add(cliff_seconds).ok_or(GeckoError::Overflow)?;
    vault.end_ts = now.checked_add(end_seconds).ok_or(GeckoError::Overflow)?;
    vault.campaign_id = campaign_id;
    vault.member_count = 0;
    vault.total_allocation_bps = 0;
    vault.status = VaultStatus::Active;
    vault.bump = ctx.bumps.vault;

    // Deposit
    token::transfer(
        CpiContext::new(
            ctx.accounts.token_program.to_account_info(),
            Transfer {
                from: ctx.accounts.sponsor_token_account.to_account_info(),
                to: ctx.accounts.vault_token_account.to_account_info(),
                authority: ctx.accounts.sponsor.to_account_info(),
            },
        ),
        amount,
    )?;

    vault.principal = amount;

    msg!(
        "Vault {} initialized and funded with {} tokens (campaign_id={})",
        vault.key(),
        amount,
        campaign_id
    );

    Ok(())
}

#[derive(Accounts)]
#[instruction(campaign_id: u64)]
pub struct InitAndDeposit<'info> {
    #[account(
        init,
        payer = sponsor,
        space = 8 + SponsorVault::INIT_SPACE,
        seeds = [VAULT_SEED, sponsor.key().as_ref(), campaign_id.to_le_bytes().as_ref()],
        bump,
    )]
    pub vault: Account<'info, SponsorVault>,

    #[account(
        init,
        payer = sponsor,
        token::mint = mint,
        token::authority = vault,
        seeds = [VAULT_TOKEN_SEED, vault.key().as_ref()],
        bump,
    )]
    pub vault_token_account: Account<'info, TokenAccount>,

    /// Sponsor's source token account
    #[account(
        mut,
        token::mint = mint,
        token::authority = sponsor,
    )]
    pub sponsor_token_account: Account<'info, TokenAccount>,

    pub mint: Account<'info, Mint>,

    #[account(
        seeds = [CONFIG_SEED],
        bump = config.bump,
    )]
    pub config: Account<'info, GeckoConfig>,

    #[account(mut)]
    pub sponsor: Signer<'info>,

    pub token_program: Program<'info, Token>,
    pub associated_token_program: Program<'info, AssociatedToken>,
    pub system_program: Program<'info, System>,
    pub rent: Sysvar<'info, Rent>,
}
