use anchor_lang::prelude::*;
use anchor_spl::{
    associated_token::AssociatedToken,
    token::{Mint, Token, TokenAccount},
};

use crate::{
    constants::{CONFIG_SEED, MIN_CLIFF_SECONDS, VAULT_SEED, VAULT_TOKEN_SEED},
    errors::GeckoError,
    state::{GeckoConfig, SponsorVault, VaultStatus},
};

/// Sponsor creates a new campaign vault.
///
/// - `campaign_id`: unique u64 chosen by the sponsor (or generated by the API)
/// - `cliff_seconds`: lock duration in seconds (minimum MIN_CLIFF_SECONDS)
/// - `end_seconds`: campaign end in seconds from now (must be >= cliff_seconds)
pub(crate) fn process(
    ctx: Context<InitVault>,
    campaign_id: u64,
    cliff_seconds: i64,
    end_seconds: i64,
) -> Result<()> {
    require!(cliff_seconds >= MIN_CLIFF_SECONDS, GeckoError::DurationTooShort);
    require!(end_seconds >= cliff_seconds, GeckoError::InvalidTimestamps);
    require!(
        ctx.accounts.config.allowed_mints.contains(&ctx.accounts.mint.key()),
        GeckoError::UnsupportedMint
    );

    let now = Clock::get()?.unix_timestamp;

    let vault = &mut ctx.accounts.vault;
    vault.sponsor = ctx.accounts.sponsor.key();
    vault.mint = ctx.accounts.mint.key();
    vault.vault_token_account = ctx.accounts.vault_token_account.key();
    vault.principal = 0;
    vault.total_yield_routed = 0;
    vault.gecko_fee_bps = ctx.accounts.config.fee_bps;
    vault.cliff_ts = now
        .checked_add(cliff_seconds)
        .ok_or(GeckoError::Overflow)?;
    vault.end_ts = now
        .checked_add(end_seconds)
        .ok_or(GeckoError::Overflow)?;
    vault.campaign_id = campaign_id;
    vault.member_count = 0;
    vault.total_allocation_bps = 0;
    vault.status = VaultStatus::Active;
    vault.bump = ctx.bumps.vault;

    Ok(())
}

#[derive(Accounts)]
#[instruction(campaign_id: u64)]
pub struct InitVault<'info> {
    #[account(
        init,
        payer = sponsor,
        space = 8 + SponsorVault::INIT_SPACE,
        seeds = [VAULT_SEED, sponsor.key().as_ref(), campaign_id.to_le_bytes().as_ref()],
        bump,
    )]
    pub vault: Account<'info, SponsorVault>,

    /// Program-owned token account holding the locked principal.
    #[account(
        init,
        payer = sponsor,
        token::mint = mint,
        token::authority = vault,
        seeds = [VAULT_TOKEN_SEED, vault.key().as_ref()],
        bump,
    )]
    pub vault_token_account: Account<'info, TokenAccount>,

    pub mint: Account<'info, Mint>,

    #[account(
        seeds = [CONFIG_SEED],
        bump = config.bump,
    )]
    pub config: Account<'info, GeckoConfig>,

    #[account(mut)]
    pub sponsor: Signer<'info>,

    pub token_program: Program<'info, Token>,
    pub associated_token_program: Program<'info, AssociatedToken>,
    pub system_program: Program<'info, System>,
    pub rent: Sysvar<'info, Rent>,
}
