use anchor_lang::prelude::*;

pub mod constants;
pub mod errors;
pub mod instructions;
pub mod state;

pub use instructions::*;

declare_id!("Eeyc1AXnQxmbMoKhJRz8g6soBpCkjwfi79DrhWwNeSh3");

#[program]
pub mod gecko_vault {
    use super::*;

    /// Initialize the singleton protocol config (admin only, called once after deploy).
    pub fn init_config(
        ctx: Context<InitConfig>,
        treasury: Pubkey,
        automation_authority: Pubkey,
        allowed_mints: Vec<Pubkey>,
    ) -> Result<()> {
        instructions::init_config::process(ctx, treasury, automation_authority, allowed_mints)
    }

    /// Sponsor creates a new campaign vault.
    ///
    /// - `campaign_id`: unique identifier for this campaign (generated by API)
    /// - `cliff_seconds`: lock duration from now (minimum 30 days)
    /// - `end_seconds`: campaign end from now (must be >= cliff_seconds)
    pub fn init_vault(
        ctx: Context<InitVault>,
        campaign_id: u64,
        cliff_seconds: i64,
        end_seconds: i64,
    ) -> Result<()> {
        instructions::init_vault::process(ctx, campaign_id, cliff_seconds, end_seconds)
    }

    /// Sponsor deposits stablecoins into the vault to fund the campaign.
    pub fn deposit(ctx: Context<Deposit>, amount: u64) -> Result<()> {
        instructions::deposit::process(ctx, amount)
    }

    /// Add a creator to the vault's squad with a yield allocation.
    ///
    /// `allocation_bps`: this creator's share in basis points (e.g. 5000 = 50%).
    /// All members' allocations must sum to 10_000 before route_yield works.
    pub fn add_creator(ctx: Context<AddCreator>, allocation_bps: u16) -> Result<()> {
        instructions::add_creator::process(ctx, allocation_bps)
    }

    /// Remove a creator from the squad and free their allocation.
    pub fn remove_creator(ctx: Context<RemoveCreator>) -> Result<()> {
        instructions::remove_creator::process(ctx)
    }

    /// Distribute yield to a single squad member (called once per member per epoch).
    ///
    /// `yield_amount`: total yield for this epoch (oracle-provided in Phase 1;
    /// derived from Kamino position delta in Phase 2).
    pub fn route_yield(ctx: Context<RouteYield>, yield_amount: u64) -> Result<()> {
        instructions::route_yield::process(ctx, yield_amount)
    }

    /// Sponsor reclaims locked principal after the cliff period.
    pub fn close_vault(ctx: Context<CloseVault>) -> Result<()> {
        instructions::close_vault::process(ctx)
    }
}
